/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        tato: {
          base: '#030a16',
          deep: '#010409',
          cyber: '#00f2ff',
          panel: '#09172d',
          panelSoft: '#12243f',
          panelDeep: '#07172d',
          panelInset: '#0b1b33',
          line: '#1c3358',
          lineSoft: '#17355f',
          lineMedium: '#21406d',
          lineBright: '#28508b',
          text: '#edf4ff',
          textSoft: '#9cb7e1',
          textHighlight: '#8ab1ff',
          muted: '#8ea4c8',
          dim: '#64779c',
          accent: '#1e6dff',
          accentStrong: '#1556d6',
          profit: '#1ec995',
          warn: '#f5b942',
          error: '#ff8f8f',
          surface: '#172338',
          hover: '#1a3158',
          cardOverlay: 'rgba(0,0,0,0.58)',
        },
      },
      borderRadius: {
        card: '30px',
      },
      fontFamily: {
        sans: ['Inter_400Regular', 'Inter', 'System'],
        'sans-medium': ['Inter_500Medium', 'Inter', 'System'],
        'sans-semibold': ['Inter_600SemiBold', 'Inter', 'System'],
        'sans-bold': ['Inter_700Bold', 'Inter', 'System'],
        mono: ['SpaceMono'],
        'outfit': ['Outfit_400Regular', 'Outfit', 'System'],
        'outfit-semibold': ['Outfit_600SemiBold', 'Outfit', 'System'],
        'outfit-bold': ['Outfit_700Bold', 'Outfit', 'System'],
        'display': ['BricolageGrotesque_800ExtraBold', 'System'],
        'display-bold': ['BricolageGrotesque_700Bold', 'System'],
      },
    },
  },
  plugins: [],
};
